# Generated by Django 3.2.12 on 2023-06-17 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Music_Lover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('audio', models.FileField(upload_to='')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.music_lover')),
            ],
        ),
        migrations.CreateModel(
            name='Folder_repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_type', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('protected', 'Protected')], default='PRIVATE', max_length=15)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music', to='app.music')),
                ('music_lover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musiclover', to='app.music_lover')),
            ],
        ),
        migrations.CreateModel(
            name='Email_Folder_conn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.ManyToManyField(related_name='EmailFolder', to='app.Email')),
                ('protect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protected', to='app.folder_repo')),
            ],
        ),
    ]
